# Generated by Django 4.0.5 on 2022-07-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('location', models.CharField(default=True, max_length=200)),
            ],
        ),
    ]
