# Generated by Django 4.0.5 on 2022-07-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_mobile_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
