# Generated by Django 4.0.5 on 2022-07-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
