# Generated by Django 4.0.5 on 2022-07-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
